
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/colin/bin/"
      - "/Users/colin/.local/bin/"
      - "/Users/colin/.local/share/uv/default-env/bin/"
      - "/Users/colin/.asdf/installs/nodejs/lts/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/colin/.asdf/shims/"
      - "/opt/homebrew/opt/asdf/libexec/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/colin/Scripts/"
      - "/Users/colin/my-cli-tools/"
      - "/Users/colin/Developer/Tools/bin/"
      - "/opt/homebrew/opt/python@3.10/bin/"
      - "/opt/homebrew/opt/openjdk/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/opt/homebrew/opt/mysql-client/bin/"
      - "/opt/homebrew/opt/libpq/bin/"
      - "/Users/colin/.lmstudio/bin/"
      - "/Users/colin/.dotnet/tools/"
      - "/opt/homebrew/opt/kubernetes-cli@1.29/bin/"
      - "/Users/colin/.krew/bin/"
      - "/Applications/Nextcloud.app/Contents/MacOS/"
      - "/Applications/IntelliJ IDEA.app/Contents/MacOS/idea/"
      - "/Users/colin/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/opt/homebrew/opt/asdf/bin/"
      - "/Users/colin/.cargo/bin/"
      - "/opt/homebrew/opt/rsync/"
    searched_directories:
      - "/Users/colin/bin/uname"
      - "/Users/colin/.local/bin/uname"
      - "/Users/colin/.local/share/uv/default-env/bin/uname"
      - "/Users/colin/.asdf/installs/nodejs/lts/bin/uname"
      - "/opt/anaconda3/condabin/uname"
      - "/Users/colin/.asdf/shims/uname"
      - "/opt/homebrew/opt/asdf/libexec/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/colin/bin"
        - "/Users/colin/.local/share/../bin"
        - "/Users/colin/.local/bin"
        - "/Users/colin/.local/share/uv/default-env/bin"
        - "/Users/colin/.asdf/installs/nodejs/lts/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/colin/.asdf/shims"
        - "/opt/homebrew/opt/asdf/libexec/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Users/colin/Scripts"
        - "/Users/colin/.local/bin"
        - "/Users/colin/my-cli-tools"
        - "/Users/colin/Developer/Tools/bin"
        - "/opt/homebrew/opt/python@3.10/bin"
        - "/opt/homebrew/opt/openjdk/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/opt/homebrew/opt/mysql-client/bin"
        - "/opt/homebrew/opt/libpq/bin"
        - "/Users/colin/.lmstudio/bin"
        - "/Users/colin/.dotnet/tools"
        - "/opt/homebrew/opt/kubernetes-cli@1.29/bin"
        - "/Users/colin/.krew/bin"
        - "/Applications/Nextcloud.app/Contents/MacOS"
        - "/Applications/IntelliJ IDEA.app/Contents/macOS/idea"
        - "/Users/colin/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/opt/homebrew/opt/asdf/bin"
        - "/Users/colin/.cargo/bin"
        - "/opt/homebrew/opt/rsync"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.0.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/colin/bin/"
      - "/Users/colin/.local/bin/"
      - "/Users/colin/.local/share/uv/default-env/bin/"
      - "/Users/colin/.asdf/installs/nodejs/lts/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/colin/.asdf/shims/"
      - "/opt/homebrew/opt/asdf/libexec/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/colin/Scripts/"
      - "/Users/colin/my-cli-tools/"
      - "/Users/colin/Developer/Tools/bin/"
      - "/opt/homebrew/opt/python@3.10/bin/"
      - "/opt/homebrew/opt/openjdk/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/opt/homebrew/opt/mysql-client/bin/"
      - "/opt/homebrew/opt/libpq/bin/"
      - "/Users/colin/.lmstudio/bin/"
      - "/Users/colin/.dotnet/tools/"
      - "/opt/homebrew/opt/kubernetes-cli@1.29/bin/"
      - "/Users/colin/.krew/bin/"
      - "/Applications/Nextcloud.app/Contents/MacOS/"
      - "/Applications/IntelliJ IDEA.app/Contents/MacOS/idea/"
      - "/Users/colin/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/opt/homebrew/opt/asdf/bin/"
      - "/Users/colin/.cargo/bin/"
      - "/opt/homebrew/opt/rsync/"
    searched_directories:
      - "/Users/colin/bin/install_name_tool"
      - "/Users/colin/.local/bin/install_name_tool"
      - "/Users/colin/.local/share/uv/default-env/bin/install_name_tool"
      - "/Users/colin/.asdf/installs/nodejs/lts/bin/install_name_tool"
      - "/opt/anaconda3/condabin/install_name_tool"
      - "/Users/colin/.asdf/shims/install_name_tool"
      - "/opt/homebrew/opt/asdf/libexec/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/colin/bin"
        - "/Users/colin/.local/share/../bin"
        - "/Users/colin/.local/bin"
        - "/Users/colin/.local/share/uv/default-env/bin"
        - "/Users/colin/.asdf/installs/nodejs/lts/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/colin/.asdf/shims"
        - "/opt/homebrew/opt/asdf/libexec/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/System/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Users/colin/Scripts"
        - "/Users/colin/.local/bin"
        - "/Users/colin/my-cli-tools"
        - "/Users/colin/Developer/Tools/bin"
        - "/opt/homebrew/opt/python@3.10/bin"
        - "/opt/homebrew/opt/openjdk/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/opt/homebrew/opt/mysql-client/bin"
        - "/opt/homebrew/opt/libpq/bin"
        - "/Users/colin/.lmstudio/bin"
        - "/Users/colin/.dotnet/tools"
        - "/opt/homebrew/opt/kubernetes-cli@1.29/bin"
        - "/Users/colin/.krew/bin"
        - "/Applications/Nextcloud.app/Contents/MacOS"
        - "/Applications/IntelliJ IDEA.app/Contents/macOS/idea"
        - "/Users/colin/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/opt/homebrew/opt/asdf/bin"
        - "/Users/colin/.cargo/bin"
        - "/opt/homebrew/opt/rsync"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
