[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "package-c"
version = "1.0.0"
description = "Math helper functions package"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "Your Team", email = "team@example.com"}]
keywords = ["example", "math", "helpers"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "tabulate>=0.9.0",
]

[project.scripts]
package-c = "package_c.__main__:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=23.0",
    "ruff>=0.1.0",
    "mypy>=1.0",
]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[project.urls]
Homepage = "https://github.com/codefuturist/monorepository-example"
Repository = "https://github.com/codefuturist/monorepository-example.git"
"Bug Tracker" = "https://github.com/codefuturist/monorepository-example/issues"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["package_c"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--cov=src --cov-report=html --cov-report=term -v"

markers = [
    "unit: Unit tests",
    "integration: Integration tests",
]

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
strict = true

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "W", "I"]

[dependency-groups]
dev = [
    "commitizen>=4.9.1",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.2.0"
tag_format = "package-c@v$version"
version_files = [
    "pyproject.toml:version",
    "src/__version__.py:__version__"
]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
changelog_start_rev = "package-c@v1.0.0"

[tool.commitizen.change_type_order]
order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf", "docs", "style", "build", "ci", "test", "chore"]
