[package]
name = "package-e"
version = "1.0.3"
edition = "2021"
authors = ["Your Team <team@example.com>"]
description = "Rust string manipulation utilities"
license = "MIT"
repository = "https://github.com/codefuturist/monorepository-example"

[[bin]]
name = "package-e"
path = "src/main.rs"

[dependencies]
colored = "2.1"
serde_json = "1.0"

[dev-dependencies]
