name: C++ Release

on:
    push:
        tags:
            - "package-d@v*.*.*"

permissions:
    contents: write

jobs:
    build-and-test:
        name: Build & Test C++ Package (${{ matrix.target }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: macos-13
                      target: x86_64-apple-darwin
                    - os: macos-latest
                      target: aarch64-apple-darwin

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install CMake
              uses: lukka/get-cmake@latest

            - name: Extract version
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/package-d@v}" >> $GITHUB_OUTPUT

            - name: Build with build script
              run: |
                  cd packages/package-d
                  chmod +x build.sh
                  ./build.sh

            - name: Test
              run: |
                  cd packages/package-d
                  ./release/package-d-${{ matrix.target }}

            - name: Upload release artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: package-d-${{ matrix.target }}
                  path: |
                      packages/package-d/release/package-d-${{ matrix.target }}*

    publish:
        name: Publish C++ Package
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Extract version
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/package-d@v}" >> $GITHUB_OUTPUT

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: dist/

            - name: Organize release files
              run: |
                  mkdir -p release
                  find dist -type f -exec mv {} release/ \;
                  ls -lh release/

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: package-d v${{ steps.version.outputs.VERSION }}
                  body: |
                      ## Package D v${{ steps.version.outputs.VERSION }}
                      
                      C++ Math Utilities
                      
                      ### Features
                      - factorial(): Calculate factorial of a number
                      - is_prime(): Check if a number is prime
                      - gcd(): Find greatest common divisor
                      - JSON output support (nlohmann/json)
                      
                      ### Downloads
                      
                      Choose the binary for your platform:
                      
                      | Platform | Architecture | File |
                      |----------|--------------|------|
                      | Linux | x86_64 | `package-d-x86_64-unknown-linux-gnu.tar.gz` |
                      | macOS | x86_64 (Intel) | `package-d-x86_64-apple-darwin.tar.gz` |
                      | macOS | aarch64 (Apple Silicon) | `package-d-aarch64-apple-darwin.tar.gz` |
                      
                      ### Verification
                      
                      Verify downloads with SHA256 checksums:
                      ```bash
                      sha256sum -c package-d-<platform>.tar.gz.sha256
                      ```
                      
                      ### Usage
                      ```bash
                      tar -xzf package-d-<platform>.tar.gz
                      ./package-d-<platform>
                      ```
                  files: |
                      release/*
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
