name: Go Release

on:
    push:
        tags:
            - "package-g@v*.*.*"

permissions:
    contents: write

jobs:
    build-and-test:
        name: Build & Test Go Package
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                go-version: ['1.21', '1.22']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Build
              run: |
                  cd packages/package-g
                  go build -v ./...

            - name: Test
              run: |
                  cd packages/package-g
                  go test -v -race -coverprofile=coverage.out ./...

            - name: Test Coverage
              if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.22'
              run: |
                  cd packages/package-g
                  go tool cover -func=coverage.out

    publish:
        name: Publish Go Package
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Create source archive
              run: |
                  cd packages/package-g
                  tar -czf package-g-${{ github.ref_name }}-source.tar.gz \
                      *.go \
                      go.mod \
                      README.md

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: package-g ${{ github.ref_name }}
                  body: |
                      ## Go Package Release

                      **Package:** package-g
                      **Version:** ${{ github.ref_name }}

                      Built and tested with Go 1.21 and 1.22 on Ubuntu, macOS, and Windows

                      ### Installation

                      ```bash
                      go get github.com/codefuturist/monorepository-example/packages/package-g@${{ github.ref_name }}
                      ```
                  files: packages/package-g/*.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
