name: Java Package Release

on:
    push:
        tags:
            - "package-h@v*.*.*"

jobs:
    build-and-test:
        name: Build and Test (Java ${{ matrix.java }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                java: ["17", "21"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.java }}
                  distribution: "temurin"
                  cache: "maven"

            - name: Extract version from tag
              id: get_version
              shell: bash
              run: |
                  TAG=${GITHUB_REF#refs/tags/package-h@v}
                  echo "VERSION=$TAG" >> $GITHUB_OUTPUT
                  echo "Extracted version: $TAG"

            - name: Build with Maven
              working-directory: packages/package-h
              run: mvn clean compile -B

            - name: Run tests
              working-directory: packages/package-h
              run: mvn test -B

            - name: Package JAR
              working-directory: packages/package-h
              run: mvn package -DskipTests -B

            - name: Upload JAR artifact
              if: matrix.os == 'ubuntu-latest' && matrix.java == '17'
              uses: actions/upload-artifact@v4
              with:
                  name: package-h-jar
                  path: packages/package-h/target/*.jar

    create-release:
        name: Create GitHub Release
        needs: build-and-test
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Extract version from tag
              id: get_version
              run: |
                  TAG=${GITHUB_REF#refs/tags/package-h@v}
                  echo "VERSION=$TAG" >> $GITHUB_OUTPUT
                  echo "Extracted version: $TAG"

            - name: Download JAR artifact
              uses: actions/download-artifact@v4
              with:
                  name: package-h-jar
                  path: ./artifacts

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: package-h v${{ steps.get_version.outputs.VERSION }}
                  body: |
                      # Package H v${{ steps.get_version.outputs.VERSION }}

                      ## Java Collection Utilities

                      A collection of utility functions for common Java collection operations.

                      ### Features
                      - **removeDuplicates**: Remove duplicate elements while preserving order
                      - **chunk**: Partition lists into chunks of specified size
                      - **mostFrequent**: Find the most frequently occurring element
                      - **interleave**: Combine two lists by alternating elements

                      ### Usage

                      ```java
                      import com.example.packageh.CollectionUtils;
                      import java.util.Arrays;
                      import java.util.List;

                      // Remove duplicates
                      List<Integer> unique = CollectionUtils.removeDuplicates(
                          Arrays.asList(1, 2, 2, 3, 3, 3)
                      );

                      // Chunk a list
                      List<List<Integer>> chunks = CollectionUtils.chunk(
                          Arrays.asList(1, 2, 3, 4, 5, 6, 7), 3
                      );

                      // Find most frequent
                      String mostCommon = CollectionUtils.mostFrequent(
                          Arrays.asList("a", "b", "a", "c", "a")
                      );

                      // Interleave lists
                      List<Integer> combined = CollectionUtils.interleave(
                          Arrays.asList(1, 3, 5),
                          Arrays.asList(2, 4, 6)
                      );
                      ```

                      ### Requirements
                      - Java 17 or higher
                      - Maven 3.6 or higher

                      ### Installation

                      Download the JAR file and add it to your classpath, or add to your Maven project:

                      ```xml
                      <dependency>
                          <groupId>com.example</groupId>
                          <artifactId>package-h</artifactId>
                          <version>${{ steps.get_version.outputs.VERSION }}</version>
                      </dependency>
                      ```

                      ### Testing

                      This release has been tested on:
                      - ✅ Ubuntu (Java 17, 21)
                      - ✅ macOS (Java 17, 21)
                      - ✅ Windows (Java 17, 21)
                  files: |
                      artifacts/*.jar
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
