name: Package E Release

on:
    push:
        tags:
            - "package-e@v*.*.*"

jobs:
    release:
        uses: ./.github/workflows/rust-package-release.yml
        with:
            package-name: package-e
            package-description: Rust String Manipulation Utilities
            package-features: |
                - reverse_string(): Reverse a string
                - count_vowels(): Count vowels in a string
                - is_palindrome(): Check if string is a palindrome
                - Colored terminal output
                - JSON output support
            usage-examples: |
                ```bash
                # Extract
                tar -xzf package-e-<platform>.tar.gz  # or unzip for Windows

                # Run
                ./package-e-<platform>
                ```
