name: Python CI

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [develop]

jobs:
    test:
        name: Test Python Packages
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.12"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build pytest pytest-cov

            - name: Install all packages
              run: |
                  for pkg in packages/*/; do
                    echo "Installing $pkg"
                    cd "$pkg"
                    pip install -e ".[test]"
                    cd ../..
                  done

            - name: Run tests
              run: |
                  for pkg in packages/*/; do
                    echo "Testing $pkg"
                    cd "$pkg"
                    pytest --cov=src --cov-report=term
                    cd ../..
                  done

            - name: Generate coverage report
              run: |
                  mkdir -p coverage-reports
                  for pkg in packages/*/; do
                    cd "$pkg"
                    pytest --cov=src --cov-report=html --cov-report=term
                    cd ../..
                  done
