name: Rust Package Release (Reusable)

on:
    workflow_call:
        inputs:
            package-name:
                description: "Name of the Rust package (e.g., package-e)"
                required: true
                type: string
            package-description:
                description: "Short description of the package"
                required: true
                type: string
            package-features:
                description: "Markdown list of package features"
                required: true
                type: string
            usage-examples:
                description: "Markdown usage examples (optional)"
                required: false
                type: string
                default: |
                    ```bash
                    # Run the application
                    ./$PACKAGE_NAME-<platform>
                    ```

# =============================================================================
# CONFIGURATION - Values that may change over time
# =============================================================================
env:
    # Build configuration (customize paths if needed)
    PACKAGES_DIR: "packages"
    RELEASE_DIR: "release"
    DIST_DIR: "dist"
    BUILD_SCRIPT: "build.sh"

# =============================================================================
# IMPLEMENTATION - Stable workflow logic (rarely changes)
# =============================================================================
permissions:
    contents: write

jobs:
    build-and-test:
        name: Build & Test (${{ matrix.target }})
        runs-on: ${{ matrix.os }}
        strategy:
            # =====================================================================
            # CONFIGURATION - Build matrix (add/remove platforms as needed)
            # =====================================================================
            matrix:
                include:
                    # Linux builds
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                    # macOS builds
                    - os: macos-13 # Intel
                      target: x86_64-apple-darwin
                    - os: macos-latest # Apple Silicon
                      target: aarch64-apple-darwin
                    # Windows builds
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: windows-latest
                      target: aarch64-pc-windows-msvc

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # =====================================================================
            # CONFIGURATION - Rust toolchain (update version as needed)
            # =====================================================================
            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable # CONFIGURATION: Can be 'stable', 'beta', 'nightly', or specific version
                  target: ${{ matrix.target }}

            - name: Extract version
              id: version
              shell: bash
              run: echo "VERSION=${GITHUB_REF#refs/tags/${{ inputs.package-name }}@v}" >> $GITHUB_OUTPUT

            - name: Build with build script
              shell: bash
              run: |
                  cd ${{ env.PACKAGES_DIR }}/${{ inputs.package-name }}
                  chmod +x ${{ env.BUILD_SCRIPT }}
                  ./${{ env.BUILD_SCRIPT }}

            - name: Test binary
              shell: bash
              run: |
                  cd ${{ env.PACKAGES_DIR }}/${{ inputs.package-name }}
                  if [ -f "${{ env.RELEASE_DIR }}/${{ inputs.package-name }}-${{ matrix.target }}.exe" ]; then
                    ./${{ env.RELEASE_DIR }}/${{ inputs.package-name }}-${{ matrix.target }}.exe || echo "Binary executed"
                  else
                    ./${{ env.RELEASE_DIR }}/${{ inputs.package-name }}-${{ matrix.target }} || echo "Binary executed"
                  fi

            - name: Upload release artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.package-name }}-${{ matrix.target }}
                  path: |
                      ${{ env.PACKAGES_DIR }}/${{ inputs.package-name }}/${{ env.RELEASE_DIR }}/${{ inputs.package-name }}-${{ matrix.target }}*

    publish:
        name: Publish Rust Package
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Extract version
              id: version
              run: echo "VERSION=${GITHUB_REF#refs/tags/${{ inputs.package-name }}@v}" >> $GITHUB_OUTPUT

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ${{ env.DIST_DIR }}/

            - name: Organize release files
              run: |
                  mkdir -p ${{ env.RELEASE_DIR }}
                  find ${{ env.DIST_DIR }} -type f -exec mv {} ${{ env.RELEASE_DIR }}/ \;
                  ls -lh ${{ env.RELEASE_DIR }}/

            # =========================================================================
            # CONFIGURATION - Release body template (customize as needed)
            # =========================================================================
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: ${{ inputs.package-name }} v${{ steps.version.outputs.VERSION }}
                  body: |
                      ## ${{ inputs.package-name }} v${{ steps.version.outputs.VERSION }}

                      ${{ inputs.package-description }}

                      ### Features
                      ${{ inputs.package-features }}

                      ### Downloads

                      | Platform | Architecture | Archive |
                      |----------|--------------|---------|
                      | Linux | x86_64 | `${{ inputs.package-name }}-x86_64-unknown-linux-gnu.tar.gz` |
                      | Linux | aarch64 (ARM64) | `${{ inputs.package-name }}-aarch64-unknown-linux-gnu.tar.gz` |
                      | macOS | x86_64 (Intel) | `${{ inputs.package-name }}-x86_64-apple-darwin.tar.gz` |
                      | macOS | aarch64 (Apple Silicon) | `${{ inputs.package-name }}-aarch64-apple-darwin.tar.gz` |
                      | Windows | x86_64 | `${{ inputs.package-name }}-x86_64-pc-windows-msvc.zip` |
                      | Windows | aarch64 (ARM64) | `${{ inputs.package-name }}-aarch64-pc-windows-msvc.zip` |

                      ### Verification

                      All downloads include SHA256 checksums for verification:
                      ```bash
                      # Linux/macOS
                      sha256sum -c ${{ inputs.package-name }}-<platform>.tar.gz.sha256

                      # Windows
                      CertUtil -hashfile ${{ inputs.package-name }}-<platform>.zip SHA256
                      ```

                      ### Usage

                      ${{ inputs.usage-examples }}
                  files: |
                      ${{ env.RELEASE_DIR }}/*
                  # CONFIGURATION: Change to true for manual approval before publishing
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
