name: Rust Release

on:
    push:
        tags:
            - "package-e@v*.*.*"

permissions:
    contents: write

jobs:
    build-and-test:
        name: Build & Test Rust Package
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable

            - name: Build
              run: |
                  cd packages/package-e
                  cargo build --release

            - name: Test
              run: |
                  cd packages/package-e
                  cargo test --release

            - name: Create package
              if: matrix.os == 'ubuntu-latest'
              run: |
                  cd packages/package-e
                  cargo package --allow-dirty

            - name: Upload artifacts
              if: matrix.os == 'ubuntu-latest'
              uses: actions/upload-artifact@v4
              with:
                  name: rust-package
                  path: packages/package-e/target/package/*.crate

    publish:
        name: Publish Rust Package
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: rust-package
                  path: dist/

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: package-e ${{ github.ref_name }}
                  body: |
                      ## Rust Package Release

                      **Package:** package-e
                      **Version:** ${{ github.ref_name }}

                      Built and tested on Ubuntu, macOS, and Windows
                  files: dist/*.crate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
